### PR TITLE
Colorize Healthbar of UnitFrames

### PR DESCRIPTION
**Pull request by Marakuja**
- still needs option etc. but this is the basic idea

I really like your addon and the way to "improve" the standard UI to feel more complete. Here is my first attempt to add something to your project and get used to all this new github stuff ;).
I can add options etc. gladly but first want to hear what you think of it.

### CODE REVIEW

**Comment by kaytotes** [comment]
Reviewing this now.

**Comment by Marakuja** [comment]
I can add the comments so it's clear what happens and would generate a "Conf_HealthBarColor" Option into the HealthBar_OnValueChanged_Hook function.

The Integration into the options panel I would leave to you, as I'm not sure if I unterstand the system you follow there correctly ;).

I can then add the german language for this option too as this is my native language.

**Comment by kaytotes** [comment]
I'll merge this after my raid night tonight :) 👍

**Comment by kaytotes** [comment]
Sorry for the delay. Merging now then adding config button.

**Pull request merged**
